baseURL = "http://blog.sakurcz.xyz"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "Sako's Blog"
copyright = "© 2025 Sako's Blog"
theme = "diary"

# Generate sitemap in the public folder
[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

# Google Analytics
[services]
  [services.googleAnalytics]
    id = "G-XXHVN7DV7P"  # Your Google Analytics ID

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = ""
enableGitalk = false
enableGiscus = true

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="Sakurc/my-blog-comments"  # 确认这是您的新仓库
    data_repo_id="R_kgDOPVuLhA"
    data_category="Announcements"          # 确保这和您在 Giscus 网站上选择的一致
    data_category_id="DIC_kwDOPVu2384CtnCH"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="zh-CN"
    crossorigin="anonymous"


[[menu.main]]
url = "/categories"
name = "分类"
weight = 1
[[menu.main]]
url = "/tags"
name = "标签"
weight = 2
[[menu.main]]
url = "/archive"
name = "归档"
weight = 3
[[menu.main]]
url = "/thanks"
name = "感谢"
weight = 4
[[menu.main]]
url = "/about"
name = "关于我"
weight = 5
